### ISSUE TITLE
potential issue with using an spiped container as a proxy for services

### ISSUE THREAD

**Issue by vikstrous** [TimWolla/docker-spiped#10]
Correct me if I'm wrong in any of the following observations:
1. The right way to use this image is to put the services on both ends of the pipe on a bridge network with spiped such that only the intended containers have access to its network
2. Docker has an issue where routing into private networks is possible from the outside on certain networks https://github.com/docker/docker/issues/14041
3. The only safe way to use this spiped image is by using unix domain sockets
4. If you want to use spiped with real network connections, you should put it inside the containers you are connecting from/to

**Comment by TimWolla** [comment]
I hope I understood your questions correctly:

> The right way to use this image is to put the services on both ends of the pipe on a bridge network with spiped such that only the intended containers have access to its network

This depends on your threat model. If you trust the containers, but not the network you can throw all the containers onto a single network. If you don’t trust the containers you need to ensure that spiped can only be accessed by the correct containers. But you would have to ensure this without spiped as well.

> Docker has an issue where routing into private networks is possible from the outside on certain networks docker/docker#14041

Unless you manually specify firewall rules this look correct to me. You are able to manually change the policy of the `FORWARD` chain using iptables, though: `iptables -P FORWARD DROP`.

> The only safe way to use this spiped image is by using unix domain sockets

Adding spiped to the stack only turns unencrypted connections into encrypted connections. If an attacker is able to connect to a container he should not be able to connect this is an issue that is orthogonal to spiped and spiped can do nothing about it.

> If you want to use spiped with real network connections, you should put it inside the containers you are connecting from/to

see 1) and 3)

**Comment by vikstrous** [comment]
Re: putting the containers on a single network

I definitely don't want a compromise of one container to lead to a compromise of the entire system, so I don't want to trust the containers more than I have to.

Re: spiped providing only encryption

Maybe I'm trying to use spiped in a way that it shouldn't be used. I'm hoping to be able to replace application level authentication by relying on spiped to make sure only containers that have access to the secret can connect to the service. Is this a bad idea?

If I can't use spiped for authentication, this limits its usefulness somewhat. Encryption on connections between nodes is already provided by docker 1.12 swarm overlay networking, so that might be a better way to get encrypted connections.

Update: Re: manually fixing the forwarding

If I do that and that works, should I still have application level authentication?

**Comment by TimWolla** [comment]
> I definitely don't want a compromise of one container to lead to a compromise of the entire system, so I don't want to trust the containers more than I have to.

The network still would be different from the system network, unless you specify host networking.

> Maybe I'm trying to use spiped in a way that it shouldn't be used. I'm hoping to be able to replace application level authentication by relying on spiped to make sure only containers that have access to the secret can connect to the service. Is this a bad idea?

This is a use case spiped can solve [1]. But you need to ensure that the only one that can communicate with your service is the spiped container (that’s what I wanted to say in my first reply with “orthogonal to spiped”). I'll try to make an analogy: Think of your service as a room you want to protect. Without spiped the room has no door and anyone can walk into it. With spiped you get a properly secured door, but this properly secured door is useless if there is another unprotected entrance into the room (the missing firewall rules).

So: You still need some basic Firewall configuration local to a single container host (namely: Ensure that spiped is the only one that may connect to your service, e.g. by using iptables or unix sockets as you suggested). That way you won’t need to maintain a list of the ip adresses of containers or services running on other hosts, but you have to keep the spiped secret safe.

[1] See: https://github.com/Tarsnap/spiped#example-usage “You can also use spiped to protect SSH servers from attackers”

> If I do that and that works, should I still have application level authentication?

I think my reply to your second quote answers this question as well.

**Comment by TimWolla** [comment]
> If I do that and that works, should I still have application level authentication?

To expand on that: Personally I trust spiped to keep my services (in my case ElasticSearch) safe. I ensured that the ElasticSearch container is properly firewalled off the malicious world and put this very spiped container in front of it. There is no other authentication.

In fact: The [ElasticSearch example in the README.md](https://github.com/TimWolla/docker-spiped/blob/master/README.md#how-to-use-this-image) of this image is copied straight from my configuration.
