### ISSUE TITLE
Alpine 3.10 image was updated

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [TimWolla/docker-spiped#31]
Alpine 3.10 image was updated with migration to 3.10.4 version.
You need to rebuild spiped image too

**Comment by TimWolla** [comment]
The builds happen by the [Docker Official Images program](https://github.com/docker-library/official-images/). The Dockerfile does not pin to a specific patch level version of Alpine. Thus this request is best directed to them. I believe these kind of rebuilds happen automatically without needing to remind them, though.
